sudo: required
language: python
services:
- docker
script:
- docker build -t halocelery .
- docker run -it --rm -e RUN_INTEGRATION_TESTS=True -e HALO_API_KEY=$HALO_API_KEY
  -e HALO_API_SECRET_KEY=$HALO_API_SECRET_KEY -e HALO_API_KEY_RW=$HALO_API_KEY -e
  HALO_API_SECRET_KEY_RW=$HALO_API_SECRET_KEY -e FIREWALL_GRAPH_GROUP=$FIREWALL_GRAPH_GROUP
  --user root -v /var/run/docker.sock:/var/run/docker.sock halocelery unbuffer /app/run-tests.sh
env:
  global:
  - FIREWALL_GRAPH_GROUP: cloudpassage/halocelery
  - secure: ZL14RAzDymaja8JPZen3woMJwjEx/2NtqH9Awq2kdslweNU+Wd1aMoH1HTRch6/lkjvYi9Nm9GP39iR0h+ySxknRxuZN06zE7G3cFfZahQoKnKsa3c3l2kmsezdqjvuOBet3/mpbVvt+VVGActGy4OawRP29d8gr16Qp/ZhIZwjmDx5334jkppdsprBb0D3o+5GFCTAfuyFJ4UyJoeROOLmRqIGk7oTWqRqSm6FauCRne1Yu4LjzwEzHPuVC2Ft+8ZLcQ/YSpQeey0MSUSSQiA3Rw94s8t9RGTyeS9jhuWq4SCFWgWugyS/a4kG1jvoZbBMcFlsnws1kkDbiV3THo9PAijxQN4T3RlhzwCcLug7Q40qIsHxTBbc7VhYmPkgZigzQHJORPqr6RwH8cDfSJ8mAaKL6xtYDJ1ueFpHI+Au0z8thZfqUhBQ6clWv2dLj3fIGSFQ+ufPAXnyGPTP5i/DReEeV2qtviTiq0h/R+Y4ha6vAxLeOtKWLiC7dLYj6ykAnH0yxyTveJDzrW13qEWJIKQ3pAdnDGXKvl2GobYex5ydRuniqgitLtwzuYm6A78XYBS+oR0j/KHEYOf83sQmUuipio2bW3PnWf0GYaw+CllXY/VO1Eun2AFYjO52qaGOrvdlgegnjeRWJGkEkMhZDIguWZNUrn3mgo2uCoGY=
  - secure: tlsnzygsORPBYdMYGbYlk4FGZ5ZRpATtWNaqBk1XjP7iddcOP8j01Ts2qwAVwEulZybI6tH48EKlXjPDiZPLMGTiFAsYgDvhvfdAtXOYGHfGyr/2PluLvOXJpYbKZh1X9zJkzxBMvx8LHFUT7f9ugW3jnDqMlGzF4zUfcMeOIWK/l6hthwIsH7XHkikruZxOvYUq26gtROuQm+4S60pQBt89fW1SDsN541JrbHDbHVKEbwUFRY+lzDEqB2EIIgRCj5yAzcbC5GoxhoEn2uZ8jIh7sodKzMwIcEVlcaPwe3lxNlVLUMGxUuRk60xlD3nuVykPb9oMrHYB7Ln2Xm2Ur901RzeT3GLaqk7zsMp+NsacFcb6fW6w4gMzkuYa1juLWSMMnRB3b+GFxgRBZ+MHOVqMhYzYchFmy/RJ5hXLJHyYqsy8Vwie8tGwwtz614PdASGbqAnNEdbrPyJactBLLEVhm5UEYhfgSi2MOthJJ+k9riqGQQ/5QA7e7NlkYK/DEzcfLPZDhtehQ0ituk8kJUFYI3zeSC5ogSzEa3faIYZ7eisl5NM9jPuC+1/7hM89jP4VdEpb0YzFHs4gqdUCtKnWbw57pliajQ9mdQ2uEMKeyTPa2IYjHTrZaQmaJG7ZgovcavhP9N6WD/BH/aF7NNFK6lBto311+ZetQjfXhGg=
