sudo: required
language: python
services:
- docker
script:
  - docker build -t halocelery .
  - docker run -it --rm -e RUN_INTEGRATION_TESTS=True -e HALO_API_KEY=$HALO_API_KEY
    -e HALO_API_SECRET_KEY=$HALO_API_SECRET_KEY -e HALO_API_KEY_RW=$HALO_API_KEY
    -e HALO_API_SECRET_KEY_RW=$HALO_API_SECRET_KEY -e FIREWALL_GRAPH_GROUP=$FIREWALL_GRAPH_GROUP
    --user root -v /var/run/docker.sock:/var/run/docker.sock halocelery /app/run-tests.sh
env:
  global:
  - FIREWALL_GRAPH_GROUP: SDK
  - secure: W48IT2V3DkcPnRnD+QJlGI3RW9+jhyAQW1FeTQSGftVIPpBFFCZB7OYo58NBdugxkIEM2JfE+roVY61D7NkfN4A0BJ/i4WCirkuiY8bheBMnUOmbRY0as723XaOQgYIeJVd6JNIaEM0zX3AerBcY0Z56ZsBGah7D8RL1mI8GPlm2SkxKYa8D8iOr/uvbioFuExt0+2YJ7jNMAkoWo1/mpIkssHDl//Qj2WH4qF2yHj3/CoDBj0LM8tODEut7KoGOBrdG8XtNxs95kdasmafVU+J/pH2CzML4635yqNklH44EPCdphZGtGr36nND60ilYXOx5UIufap6hVENAKzJtKb8rvMy5fAVGNTGJnZPCABAoajqb6hhgeWAZkAnbjSLCUwpLNHhvvGhubRV6OG0zJ038XZsGZRySWqKkdI2keYj+XMgFXrSTeTYUyP9eiFpNdpScMeH+G2rD2QVfsNrobuxiCpzYuoBzUV02mpcbsGnNIGNsjaaD3W5leTfpOTE2vpsH+7CgBNhPzlkBv7ZJE9e4BGqoK21V7pKMr/w6iShOakxcP4Ehb0z3ZJEFp6EqtHY9dL1vLzIsbNwriyDSNiUfeW2HffX60pmceUKu78lwcuoA14JgqB3T4aHavQm2poWqgR6UZeQVh4xYWHMhg9rmx/YvldUXnFJTD9iHfTo=
  - secure: a+6rl+SJ5ApCAvvV/FnGQ2+GOxrYPvPqF1l29o4T+Pw+aeAdULgNtpavSBTM7oj/QxApdlaRS7viXk/qu6GHQmSv2ox1iH8Lb1swipcN03KmJH295coM9DiYZzpKaQTGBQ1S5CrLrfkjbDKLmjnjJTi4lGRc56zT022yMCTlfyC3GejWjh75bo1l+5fm8TEObZ+2EBYSbB48aaJhha9qw0QfU+9X/ycdx6AaA5MCSa7RCTRCL9flVlCB+3ZaCCGdSMPaX63Flhsb+Ts4M1NCqj2rCJ9/w++xFhgjaZSBzb+DTzG05/ZtWvvJxHAALejNMEZf2Fb6HPQSuFFjkFC/PI/PV5+3fVVpPrvKqSHyyGn2qcnX+ZIUptjJzsUMVOvmHkn6QBIVB9Anmf4c92BCKXwC8MkKp9TTn6LH/NgbQDDf8m1UMHewQB0/nPQdqC/LNLUMWBWXfJT3ZxWgz8P1wLkbU5JCFDLCqE9Kx8CnokBV3UO+D1Ya65WU9QK0N0hUaasPnRTTFZA1Pr3Q+lpU6YbSuHgcgazfi5q1u3lGjzRlMF7DC4IGX0nxF22CpP+3Yi+EGggpIagjSvCHMhuhXf5FFSmtkRrL29r9byFfycJudlaCTb62r3xFU7+xHRvadE1Am2uz+DRdYdEA3nN1e3w8xB61GrQGAIb+qbvEfF4=
