sudo: required
language: python
services:
- docker
script:
- docker build -t halocelery .
- docker run -it --rm -e RUN_INTEGRATION_TESTS=True -e HALO_API_KEY=$HALO_API_KEY
  -e HALO_API_SECRET_KEY=$HALO_API_SECRET_KEY -e HALO_API_KEY_RW=$HALO_API_KEY -e
  HALO_API_SECRET_KEY_RW=$HALO_API_SECRET_KEY -e FIREWALL_GRAPH_GROUP=$FIREWALL_GRAPH_GROUP
  --user root -v /var/run/docker.sock:/var/run/docker.sock halocelery unbuffer /app/run-tests.sh
env:
  global:
  - FIREWALL_GRAPH_GROUP: halocelery-lin
  - secure: FEg9+PVmWAeYc/HIEo1/PNMUyBSEboTCoz9RWvZ3wFp+8nlYZOM0ID0E0UrZck5bkrVVOIycC3YpSJFD5ihNfx1stMp23kOLRJBuqANgmQkXVKOoqgnBwQRSPqB2rlW5142j4vS0KfRCHFnH+WEq4bN67Og46h4/EprYaZoLLcTReEfBycybxI86QaQNMyaU0eNnK8XkcOn1MXL2cyhKkKwllIqfIrGp2XAfbgs/PdHbhCxFCNOmSAYBklNsXfGmM6wY6XWJO0OnB69zW7PDffetZHGVuNhGirYz3X+TPs5tWAln7khyDf8tuJouIm5a8Os9+QuUu/Md98uLFaJoWiISYXbZS1mNCbNe/XI7GpzF7+ZI1wFpOkJ2Bo63TLpPUxIVhg5o3uqudKiPDvbKbVqDu6t+nmRbPyGP2goxXgbMCL5jhszjgAWYaX8wfNcuxcGrmZqd/1YeQLhah5LRBFMOEJ8FRVZ8Wd2NDg2ef7Gt5CpGZLdUBoumD/k/YSrOy6+6HXgQ8U+fSra7zKcpkxJr6VrHq46nz8VxZrGnVLbhAk6jZzUOhWcCP0UeSfR1nDbMsa63SnVvyr/3ZjrJ52P47CVuwiu/r7hJnTOCfjHRLSeAA3JcSkw5d7v7XkYJmeBPMpQUYb/RVrlql63JxqXcADwWeg4DtsxRQFe/+xo=
  - secure: rBp/Md62v7+uAxlaqNZ0qKWLdJe+ZfzkuNDHiLW4dsfD9hUQ4DFtO9miw5y7K+yi47EAzzK6KQyuD7vYeLZ3MZ+UM62DIja/C8QwPAs5RM1xO2n7BgEEZAtOixjCwU7DmG3djL3xhZy6Y+47sq1N8/tN1JTf+ioLmlqR/Z6kHm9QZLouLsp3hwUDv0awrdoNcusVPcIHCZpz7/1PVjRxFKddgcgBbGrxJlgG392nEnJgJCwLna9cNpamOacaWO1NZWHd8VC5QzuhgIEfM9134n9nv52wKrQt3qkoaMWO7iPSKOr3lQrbc/QEir/YrMwFcfI8eDH1eGwgCrzIw8eMfTOAC16ljCkyiPB2sFJt7rI/x+WqZ2gv3klDjqu3rxHOhEY3kcrFc+5OXlHelCxL/KXi94X58eshwaVvSLYK9t5ZQf6QKniu9zFyEU2vxAw+R8ydAMoXZl2sgFBl3LrfURkxcj+YHtjoSv9W0jIEhpSfcxDYvBI96rMQ5v9xs8XUXijM02FNwmzDjtXEWDcFi3IiLFiUaEp1tEv7GAffGenqAPn2/BGevyGzBbSXJWKYpix5NYXRZxlOstb1Mf/X1iSk7WE+byxfksnshNikXA0zQ/0Mu2iS3xi5Jq1n3/qQ2T15cQDYhWcaGi1Dja+RPivaeKhrixxT1nPcpr9+zMY=
